Working AT Tracking
FRC4913/Centerstage pull request #16
Opened 2023-09-22 04:35 UTC by pairnon

Updated code showcased at BSN

2023-09-22 17:32 UTC, chrysaliszt requested changes

2023-09-22 17:32 UTC, chrysaliszt commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/huskyteers/HuskyTeleOpMode.java
Telemetry needs some changes. 
- Remove unnecessary data like "left bumper" 
- Clean up the "drive", "strafe" and "turn" data during AprilTag alignment
- Implement multiple AprilTag data printing using a "for each" loop

Add a toggle to switch between field-centric and robot-centric controls.

Everything else in this file looks good to me.

2023-09-22 17:32 UTC, chrysaliszt commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/huskyteers/HuskyVisionTestingAuto.java
Review if this file is still necessary. It has mostly been adapted into our teleop.

2023-09-22 17:32 UTC, chrysaliszt commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/huskyteers/WheelDiagnosticsOpMode.java
Verify that this file works. Fix style/conventions issues.

2023-09-22 17:32 UTC, chrysaliszt commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/huskyteers/vision/SideAprilTagDetection.java
Do we need separate files for side AprilTag vs. backdrop AprilTag detection?

2023-09-22 17:59 UTC, ethansocal commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/huskyteers/HuskyVisionTestingAuto.java
I don't think so, I'll delete it

2023-09-22 18:00 UTC, ethansocal commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/huskyteers/HuskyTeleOpMode.java
I think we should remove the currentGamepad1 and currentGamepad2, they seem to be useless

2023-09-22 18:37 UTC, TheHuskyteers commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/huskyteers/HuskyTeleOpMode.java
currentGamepad1 and currentGamepad2 will be used later for toggle features. We will add previousGamepad1 and 2, which can be used to compare gamepad states for falling/rising edge detectors.

2023-09-22 18:43 UTC, chrysaliszt commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/huskyteers/HuskyTeleOpMode.java
currentGamepad1 and currentGamepad2 will be compared to the previous gamepad state to allow "toggle" features. You can remove them if you'd like, but we'll need to add it back in anyways.

Also, each call to the gamepad hardware takes up some time as the robot communicates with the hardware. It's best practice to only communicate with the gamepad once to store it, and then use inputs from the store memory object rather than making hardware calls every time we need to get an input.

2023-09-25 23:10 UTC, chrysaliszt approved these changes

2023-09-25 23:16 UTC, merged